package com.socialmedia.petTreff.entity;

public enum NotificationType {
    FRIEND_REQUEST_CREATED,
    FRIEND_REQUEST_ACCEPTED,
    FRIEND_REQUEST_DECLINED,
    GENERAL, FRIEND_REQUEST, CHAT_MESSAGE,
    MATCH_INTEREST,
    MATCH_INTEREST_ACCEPTED,
    MATCH_INTEREST_DECLINED,
}
